### ISSUE TITLE
Broken build with XCode 5.1 for iOS7.1

### ISSUE THREAD

**Issue by maksimorlovich** [SVProgressHUD/SVProgressHUD#252]
SVProgressHUD.m:33:1: error: duplicate declaration of method 'showProgress:status:maskType:'
- (void)showProgress:(float)progress
  ^

showProgress instance method should match class method and use CGFloat instead of float, as on arm64, CGFloat is defined as double and causes build break. Easy fix though.
