### ISSUE TITLE
Duplicate symbols build error in v2.0.1

### ISSUE THREAD

**Issue by pwillsey** [SVProgressHUD/SVProgressHUD#587]
After updating to 2.0.1 I get duplicate symbol errors when I try and build:

duplicate declaration of method 'backgroundRingView'
duplicate declaration of method 'ringView'

I think there is an extra declaration of the property getter in the header file, here's a PR

https://github.com/SVProgressHUD/SVProgressHUD/pull/586

**Comment by Trancephp** [comment]
I met the same problem also

**Comment by CroPort** [comment]
I created a new Project just now,after install 2.0.1 to my  project,I get the same errors as they are.

**Comment by teerayuthton** [comment]
i met same problem with XCode 7.2
after i update my os x 10.11 to 10.11.4 and update XCode 7.2 to 7.3
i can build project and this issue has solved
